vsgSite/Customer/urls.py
from django.urls import path

from . import views

app_name = 'Customer'
urlpatterns = [
    # ex: /Customer/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /Customer/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:pk>/spinup/', views.spinup, name='spinup'),
]

vsgSite/vsgLicense/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /vsgLicense/
    path('', views.index, name='index'),
    # ex: /vsgLicense/5/
    path('<int:customer_id>/', views.detail, name='detail'),
    # ex: /vsgLicense/5/results/
    path('<int:customer_id>/results/', views.results, name='results'),
    # ex: /vsgLicense/5/spinup/
    path('<int:customer_id>/spinup/', views.spinup, name='spinup'),
]

vsgSite/vsgSite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('Customer.urls')),
    path('Customer/', include('Customer.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

vsgSite/Customer/models.py
from django.db import models
from datetime import datetime

class Customer(models.Model):
    cust_id = models.CharField(max_length=100)
    cust_name = models.CharField(max_length=100)
    add_date = models.DateTimeField('date added', default=datetime.now, blank=True)
    # Metadata
    class Meta:
        ordering = ['cust_name']
    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.cust_name

class License(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    license_no = models.CharField(max_length=100)
    license_in_use = models.BooleanField()
    active_ind = models.BooleanField(default=True)
    replay_ind = models.BooleanField(default=True)
    studio_ind = models.BooleanField(default=True)
    review_ind = models.BooleanField(default=True)
    slomo_ind = models.BooleanField()
    dante_ind = models.BooleanField()
    uhd_ind = models.BooleanField()
    add_date = models.DateTimeField('date added', default=datetime.now, blank=True)
    # Metadata
    class Meta:
        ordering = ['license_no']
    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.license_no

class Proxy(models.Model):
    license = models.ForeignKey(License, on_delete=models.CASCADE)
    ip_in = models.GenericIPAddressField(blank=True, null=True)
    ip_out = models.GenericIPAddressField(blank=True, null=True)
    mac_address = models.CharField(max_length=32)
    program_id = models.CharField(max_length=100)
    program_name = models.CharField(max_length=100)
    io_mode = models.CharField(max_length=10)
    add_date = models.DateTimeField('date added', default=datetime.now, blank=True)
    # Metadata
    class Meta:
        ordering = ['program_name']
    def __str__(self):
        """String for representing the MyModelName object (in Admin site etc.)."""
        return self.id

vsgSite/Customer/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from .models import Customer, License
from .utils import *
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin


class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'Customer/index.html'
    context_object_name = 'latest_customer_list'

    def get_queryset(self):
        return Customer.objects.all()

class DetailView(LoginRequiredMixin, generic.DetailView):
    model = Customer
    template_name = 'Customer/detail.html'

class ResultsView(LoginRequiredMixin, generic.DetailView):
    model = Customer
    template_name = 'Customer/results.html'

def spinup(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    customer_txt = str(customer_id)

    if request.POST:
        src = os.path.join(settings.STATIC_PATH,'AWSProxy.bat')
        dest = tmpFileName(customer_txt)
        dest.close()
        CopyFile(src, dest.name)
        try:
            exec(dest.name, customer_txt)
        except:
            print("Something went wrong")
        finally:
            os.remove(dest.name)
    return render(request, 'Customer/detail.html', {'customer': customer})

def results(request, customer_id):
    response = "You're looking at the nodes for customer %s."
    return HttpResponse(node % customer_id)

vsgSite/Customer/templates/Customer/detail.html
{% extends "base_generic.html" %}

{% block content %}


<body  onpageshow="getIPFromAmazon()">
    <h2>{{ customer.cust_name }}</h2>
    Customer since {{ customer.add_date }}<br/>
    <form action="{% url 'Customer:detail' customer.id  %}spinup/" method="POST">
    {% csrf_token %}

    <div style="margin-left:20px;margin-top:20px">
        <h4>Licenses</h4>
        <ul>
        {% for lic in customer.license_set.all %}
            {% if lic.active_ind %}
            <li><b>#</b> {{lic.license_no}}  {% if lic.license_in_use %}In Use{% else %}Available{% endif %} <i>(Added {{lic.add_date}})</i><br/>
                <b>Features: </b>
                {% if lic.replay_ind %}Replay /{% else %}{% endif %}
                {% if lic.studio_ind %}Studio /{% else %}{% endif %}
                {% if lic.review_ind %}Review /{% else %}{% endif %}
                {% if lic.slomo_ind %}Slo-mo /{% else %}{% endif %}
                {% if lic.dante_ind %}Dante /{% else %}{% endif %}
                {% if lic.uhd_ind %}UHD {% else %}{% endif %}
                {% if lic.license_in_use %}<button type="submit">Shut Down</button>{% else %}<button type="submit">Launch</button>{% endif %}
                <br/><br/>
           </li>
            {% endif %}
        {% endfor %}
        </ul>
    </div>
    Your IP is <input type="text" id="myip" name="myip" value=""/><br/>
    </form>

<script>
function getIPFromAmazon() {
  myURL = "https://checkip.amazonaws.com/";
  myURL = "https://ipinfo.io/ip";
  fetch(myURL,
      { headers: {'Content-Type': 'Access-Control-Allow-Origin'}, mode: 'cors', credentials: 'same-origin'})
    .then(res => res.text())
    .then(data => document.getElementById("myip").value = data)

}

function myIP() {
  document.getElementById("myip").value = getIPFromAmazon();
}
document.getElementById("myip").onload = function() {getIPFromAmazon()};
</script>

{% endblock %}

vsgSite/Customer/templates/Customer/index.html
{% extends "base_generic.html" %}

{% block content %}

    <title>Customers</title>

    {% if latest_customer_list %}
        <ul>
        {% for customer in latest_customer_list %}
            <li><a href="{% url 'Customer:detail' customer.id %}">{{ customer.cust_name }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No customers are available.</p>
    {% endif %}

{% endblock %}

vsgSite/Customer/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Customer Licenses</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="sidebar-nav">
          <li><a href="/Customer">Home</a></li>
          <li><a href="/Customer">All Customers</a></li>
          <li><a href="/admin">Admin</a></li>
          {% if user.is_authenticated %}
          <li>User: {{ user.get_username }}</li>
          <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
          {% endif %}
        </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>